version: 2.1
jobs:
  build:
    docker:
      # new all-in-one docker image
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'android-9.0'
      #PBRP_BRANCH: 'reza'
      VERSION: '3.0.0'
      MAINTAINER: '@Reza_Adi_Pangestu'
      VENDOR: 'xiaomi'
      CODENAME: 'whyred'
      BUILD_LUNCH: 'omni_whyred-eng'
      # Remove the following when Publishing Official
      # TEST_BUILD: 'true'
      # Only for Official Build, uncomment following
      PB_OFFICIAL: 'true'
      CHANGELOG: |
        - Update based 3.5.0
        - Update lock pattern types for A11
        - Improve logd
        - Support delayed adopted storage mount
        - Support new Magisk.apk installed
        - Refresh system details after sideload and wipe system
        - Restore context for SAR
        - Misc
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
            echo "Set GitAuth Infos too"
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global color.ui true
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_utils/pb/build.sh
            source build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: android-9.0
          context: org-global
